/**
 * Built-in premade beasts.
 *
 * These are always available in the beast selector, regardless of
 * whether the player has sculpted any custom beasts. Phase 2 ships
 * with two (one biped, one quadruped) so we can demo both archetypes.
 * Future phases add more (Chonkus, Skitter, Sir Slime, etc).
 */

import type { BeastDefinition } from './beast-data';

export const PREMADE_BEASTS: BeastDefinition[] = [
  {
    id: 'chonkus',
    name: 'Chonkus',
    description: 'Chunky pink tank. Big floppy arms hit hard if you spin into someone.',
    archetype: 'bipedal',
    isDefault: true,
    personality: 'tank',
    hasArms: true,
    weightClassHint: 'heavy',
    playstyleSummary: 'Slow tank with a big right-arm punish swing.',
    attackSlots: [
      {
        id: 'primary',
        appendageRoot: 'shoulder_r',
        drivenJoints: ['shoulder_r', 'elbow_r'],
        hitSegments: ['shoulder_r', 'elbow_r'],
        activeBodies: ['shoulder_r', 'elbow_r'],
        visualRigType: 'overhand_smash',
        profile: 'blunt',
        windupPose: { shoulder_r: 2.15, elbow_r: -1.85 },
        strikePose: { shoulder_r: -0.95, elbow_r: -0.3 },
        recoverPose: { shoulder_r: 0.65, elbow_r: -0.85 },
        windupTime: 0.22,
        recoverTime: 0.34,
        minHoldForCharge: 0.02,
        maxChargeTime: 0.9,
        holdDrainPerSec: 6.5,
        strikeCostLight: 11,
        strikeCostHeavy: 20,
        damageMulLight: 0.9,
        damageMulHeavy: 1.35,
        knockbackMul: 1.3,
        rootLungeForward: 1.8,
        rootLungeUp: 0.2,
        rootYawAssist: 0.4,
        braceDriveMultiplier: 0.52,
        braceTurnMultiplier: 1.7,
        braceSupportMultiplier: 1.2,
        braceUprightMultiplier: 1.22,
        braceBrakeMultiplier: 1.55,
      },
    ],
    visuals: {
      color: 0xdd4444,
      emissive: 0x330808,
      torsoScale: 1.0,
      iconEmoji: '🥩',
    },
  },
  {
    id: 'stomper',
    name: 'Stomper',
    description: 'Four legs, one brain, and a deeply unreasonable stride.',
    archetype: 'quadruped',
    isDefault: true,
    personality: 'bully',
    weightClassHint: 'heavy',
    playstyleSummary: 'Stable shover that opens foes with body bashes.',
    attackSlots: [
      {
        id: 'primary',
        appendageRoot: 'torso',
        drivenJoints: ['hip_fl', 'hip_fr', 'knee_fl', 'knee_fr'],
        hitSegments: ['torso', 'hip_fl', 'hip_fr'],
        activeBodies: ['torso', 'hip_fl', 'hip_fr'],
        blockBodies: ['torso', 'hip_fl', 'hip_fr'],
        visualRigType: 'forequarters_shove',
        profile: 'shield',
        windupPose: { hip_fl: 0.65, hip_fr: 0.65, knee_fl: -0.75, knee_fr: -0.75 },
        strikePose: { hip_fl: -0.85, hip_fr: -0.85, knee_fl: -0.2, knee_fr: -0.2 },
        recoverPose: { hip_fl: 0.2, hip_fr: 0.2, knee_fl: -0.5, knee_fr: -0.5 },
        windupTime: 0.2,
        recoverTime: 0.28,
        minHoldForCharge: 0.03,
        maxChargeTime: 0.8,
        holdDrainPerSec: 5.5,
        strikeCostLight: 9,
        strikeCostHeavy: 16,
        damageMulLight: 0.75,
        damageMulHeavy: 1.05,
        knockbackMul: 1.45,
        rootLungeForward: 1.6,
        rootLungeUp: 0.12,
        rootYawAssist: 0.2,
        braceDriveMultiplier: 0.42,
        braceTurnMultiplier: 1.55,
        braceSupportMultiplier: 1.32,
        braceUprightMultiplier: 1.28,
        braceBrakeMultiplier: 1.7,
      },
    ],
    visuals: {
      color: 0xc85a3a,
      emissive: 0x2a0808,
      torsoScale: 1.1,
      iconEmoji: '🐂',
    },
  },
  {
    id: 'noodlesnake',
    name: 'Noodlesnake',
    description: 'Wobbly biped with windmilling arms. Fast, fragile, slappy.',
    archetype: 'bipedal',
    isDefault: true,
    personality: 'skirmisher',
    hasArms: true,
    weightClassHint: 'light',
    playstyleSummary: 'Fast poke fighter that needs cleaner alignments.',
    attackSlots: [
      {
        id: 'primary',
        appendageRoot: 'shoulder_l',
        drivenJoints: ['shoulder_l', 'elbow_l'],
        hitSegments: ['elbow_l'],
        activeBodies: ['elbow_l'],
        visualRigType: 'arm_chain_spike',
        tipSegment: 'elbow_l',
        tipLocalOffset: { x: 0, y: -0.17, z: 0.1 },
        profile: 'spike',
        windupPose: { shoulder_l: -2.05, elbow_l: -0.2 },
        strikePose: { shoulder_l: 1.2, elbow_l: -1.45 },
        recoverPose: { shoulder_l: -0.65, elbow_l: -0.7 },
        windupTime: 0.15,
        recoverTime: 0.24,
        minHoldForCharge: 0.01,
        maxChargeTime: 0.75,
        holdDrainPerSec: 4.8,
        strikeCostLight: 7,
        strikeCostHeavy: 12,
        damageMulLight: 0.85,
        damageMulHeavy: 1.25,
        knockbackMul: 0.92,
        rootLungeForward: 1.3,
        rootLungeUp: 0.16,
        rootYawAssist: 0.28,
        braceDriveMultiplier: 0.62,
        braceTurnMultiplier: 1.9,
        braceSupportMultiplier: 1.14,
        braceUprightMultiplier: 1.16,
        braceBrakeMultiplier: 1.36,
      },
    ],
    visuals: {
      color: 0xe88b5a,
      emissive: 0x2e1608,
      torsoScale: 0.9,
      iconEmoji: '🌭',
    },
  },
  {
    id: 'butterchonk',
    name: 'Butterchonk',
    description: 'Smooth pale quadruped, deceptively heavy.',
    archetype: 'quadruped',
    isDefault: true,
    personality: 'tank',
    weightClassHint: 'superheavy',
    playstyleSummary: 'Very heavy bruiser with slower shield-style drives.',
    attackSlots: [
      {
        id: 'primary',
        appendageRoot: 'torso',
        drivenJoints: ['hip_fl', 'hip_fr', 'knee_fl', 'knee_fr'],
        hitSegments: ['torso', 'hip_fl', 'hip_fr'],
        activeBodies: ['torso', 'hip_fl', 'hip_fr'],
        blockBodies: ['torso', 'hip_fl', 'hip_fr'],
        visualRigType: 'forequarters_shove',
        profile: 'shield',
        windupPose: { hip_fl: 0.55, hip_fr: 0.55, knee_fl: -0.8, knee_fr: -0.8 },
        strikePose: { hip_fl: -0.75, hip_fr: -0.75, knee_fl: -0.1, knee_fr: -0.1 },
        recoverPose: { hip_fl: 0.12, hip_fr: 0.12, knee_fl: -0.52, knee_fr: -0.52 },
        windupTime: 0.24,
        recoverTime: 0.36,
        minHoldForCharge: 0.04,
        maxChargeTime: 0.9,
        holdDrainPerSec: 6.1,
        strikeCostLight: 11,
        strikeCostHeavy: 18,
        damageMulLight: 0.72,
        damageMulHeavy: 1.02,
        knockbackMul: 1.5,
        rootLungeForward: 1.7,
        rootLungeUp: 0.15,
        rootYawAssist: 0.18,
        braceDriveMultiplier: 0.38,
        braceTurnMultiplier: 1.4,
        braceSupportMultiplier: 1.34,
        braceUprightMultiplier: 1.3,
        braceBrakeMultiplier: 1.85,
      },
    ],
    visuals: {
      color: 0xe8c080,
      emissive: 0x2a1a08,
      torsoScale: 1.2,
      iconEmoji: '🧈',
    },
  },
];

/** Look up a premade beast definition by id. Returns undefined if missing. */
export function getPremade(id: string): BeastDefinition | undefined {
  return PREMADE_BEASTS.find((b) => b.id === id);
}

/** Default beast to select on homepage open. */
export const DEFAULT_BEAST_ID = 'chonkus';
